name: build-iso
on:
  workflow_dispatch: 

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    # strategy:
    #   fail-fast: false

      # matrix:
      #   recipe:
      #     - recipe.yml

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install bluebuild cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: blue-build

      - name: Generate ISO
        run: |
          sudo -E /home/runner/.cargo-install/blue-build/bin/bluebuild -v generate-iso --iso-name ${{ github.event.repository.name }}-latest.iso image ghcr.io/vorxiu/ublue-niri:latest
      # - name: Build ISO
      #   id: build
      #   uses: jasonn3/build-container-installer@main
      #   with:
      #     image_name: ublue-niri
      #     image_repo: ghcr.io/vorxiu
      #     image_tag: latest
      #     version: 43
      #     # variant: silverblue
      #     iso_name: ${{ github.event.repository.name }}-latest.iso
      #     web_ui: true
    

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-latest-iso
          path: ./*.iso
          if-no-files-found: error
          compression-level: 10
          retention-days: 30

      - name: Upload checksum as artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-latest-checksum
          path: ./*-CHECKSUM
          if-no-files-found: error
          retention-days: 30
