name: build-iso
on:
  workflow_dispatch: 

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml

    steps:
      # - name: Maximize build space
      #   uses: ublue-os/remove-unwanted-software@v7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bluebuild cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: blue-build
          args: "--locked"

      - name: Generate ISO
        run: |
          sudo bluebuild generate-iso --iso-name ${{ github.event.repository.name }}-latest.iso --output-dir ./output image ${{ env.IMAGE_REGISTRY }}/${{ github.event.repository.name }}:latest

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-latest-iso
          path: ./output/*.iso
          if-no-files-found: error
          retention-days: 7

      - name: Upload checksum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-latest-checksum
          path: ./output/*-CHECKSUM
          if-no-files-found: error
          retention-days: 7

      - name: Upload ISO to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: ./output/*.iso
          folderId: ${{ secrets.FOLDER_ID }}
          name: ${{ github.event.repository.name }}-latest.iso
          overwrite: "true"
