name: build-iso-titanoboa
on:
  workflow_dispatch: 

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ghcr.io/vorxiu/ublue-niri:latestrootfs-install-livesys-scripts
          # flatpaks-list: ${{ github.workspace }}/flatpaks/system-flatpaks.list
          hook-post-rootfs: ${{ github.workspace }}/files/scripts/configure_iso.sh
          kargs: ""
          builder-distro: fedora
          livesys: false

      - name: Rename and Checksum ISO
        run: |
          mkdir -p output
          mv ${{ steps.build.outputs.iso-dest }} output/${{ github.event.repository.name }}-latest-titanoboa.iso
          (cd output && sha256sum ${{ github.event.repository.name }}-latest-titanoboa.iso | tee ${{ github.event.repository.name }}-latest-titanoboa.iso-CHECKSUM)

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-latest-iso
          path: output/*.iso
          if-no-files-found: error
          retention-days: 7

      - name: Upload checksum as artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}-latest-checksum
          path: output/*-CHECKSUM
          if-no-files-found: error
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: ISO Build ${{ github.run_number }}
          files: |
            output/*.iso
            output/*-CHECKSUM
          draft: false
          prerelease: false

